print("***CALCULATOR***")
print(" ")
num1=input("Enter a number: ")
num2=input("Enter antoher number: ")

p_result=float(num1)+float(num2)
m_result=float(num1)-float(num2)
t_result=float(num1)*float(num2)
d_result=float(num1)/float(num2)
print("**RESULTS**")
print("collection result " + str(p_result))
print("result of extraction " + str(m_result))
print("result of multiplication " + str(t_result))
print("result of division " + str(d_result))